// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dygdcxpcpawkjwqyjysl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5Z2RjeHBjcGF3a2p3cXlqeXNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODUzMDcsImV4cCI6MjA2NjI2MTMwN30.V1c7oYOXBVH6NiYuDv3Q1gC9PeEmDXtZQac1yLA9-Mg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);